<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'RestResource\Module'                        => __DIR__ . '/Module.php',
    'RestResource\Controller\WebUiController' => __DIR__ . '/src/RestResource/Controller/WebUiController.php',
    'PasteTest\Framework\TestCase'        => __DIR__ . '/tests/RestResource/Framework/TestCase.php',
    'PasteTest\SampleTest'                => __DIR__ . '/tests/RestResource/SampleTest.php',
);
