<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Paste\Module'                        => __DIR__ . '/Module.php',
    'Paste\Controller\WebUiController' => __DIR__ . '/src/Paste/Controller/WebUiController.php',
    'PasteTest\Framework\TestCase'        => __DIR__ . '/tests/Paste/Framework/TestCase.php',
    'PasteTest\SampleTest'                => __DIR__ . '/tests/Paste/SampleTest.php',
);
