<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Mapper\Module'                        => __DIR__ . '/Module.php',
    'Mapper\Controller\InstructionsController' => __DIR__ . '/src/Mapper/Controller/InstructionsController.php',
    'MapperTest\Framework\TestCase'        => __DIR__ . '/tests/Mapper/Framework/TestCase.php',
    'MapperTest\SampleTest'                => __DIR__ . '/tests/Mapper/SampleTest.php',
);
