<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DoctrineTest\Module'                        => __DIR__ . '/Module.php',
    'DoctrineTest\Controller\SkeletonController' => __DIR__ . '/src/DoctrineTest/Controller/SkeletonController.php',
    'DoctrineTestTest\Framework\TestCase'        => __DIR__ . '/tests/DoctrineTest/Framework/TestCase.php',
    'DoctrineTestTest\SampleTest'                => __DIR__ . '/tests/DoctrineTest/SampleTest.php',
);
